In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
b = a[:2]
print(a, b) 
b[0] = -1
print(a, b)
b = a[::]
print(b)
b = a.copy()
print(b)
b[0] = 1
print(a, b)

[1 2 3 4] [1 2]
[-1  2  3  4] [-1  2]
[-1  2  3  4]
[-1  2  3  4]
[-1  2  3  4] [1 2 3 4]


In [21]:
a = np.array([0,1,2,3,4])
a[-2:] = [-1, -2]
print(a)
a[-2:] = 99
print(a)
print(a[0])
print(a.__getitem__(0))
#a[0] == a.__getitem__(0)
a[0] = 100
print(a)
a.__setitem__(0, 1020)
print(a)
#a[0] = 100 is equals to a.__setitem__(0, 100)
## __is called Dunder __main__ is Dunder main Dunder

[ 0  1  2 -1 -2]
[ 0  1  2 99 99]
0
0
[100   1   2  99  99]
[1020    1    2   99   99]


In [41]:
a = np.arange(0, 80, 10)
indices = [1,2,-3]
y = a[indices]
print(y, "\n", a)
a[indices] = 99
print(a)
a[indices] = y
print(a)
mask = np.array([0,1,1,0,0,1,0,0], dtype=bool)
y = a[mask]
print()
print(y)
a = np.array([-1,-31,4,-6,9,3])
neg = a < 0
print(neg)
a[neg]

[10 20 50] 
 [ 0 10 20 30 40 50 60 70]
[ 0 99 99 30 40 99 60 70]
[ 0 10 20 30 40 50 60 70]

[10 20 50]
[ True  True False  True False False]


array([ -1, -31,  -6])

In [61]:
a = np.arange(25).reshape(5, 5)
a[[0,2,3,3],[2,3,1,4]]
filt = (a % 3 == 0)
print(a[filt])
print(a % 3)

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]]
[ 0  3  6  9 12 15 18 21 24]
[[0 1 2 0 1]
 [2 0 1 2 0]
 [1 2 0 1 2]
 [0 1 2 0 1]
 [2 0 1 2 0]]


In [75]:
a = np.array([0,0,0,10,10,10,20,20,20,30,30,30]).reshape(4,3)
b = np.array([0,1,2,0,1,2,0,1,2,0,1,2]).reshape(4,3)
a + b[0]

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [68]:
a = np.ones((3, 5)); b = np.ones((5,))
b.reshape(1,5)
b[np.newaxis, :]

array([[1., 1., 1., 1., 1.]])

In [82]:
a = np.array([[1,2,3],[4,5,6]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=-1)) ## always columns

21
[5 7 9]
[ 6 15]
[ 6 15]


In [91]:
a = np.ones((5,6))
print(a.shape)
a.sum(axis=0)
print(a.sum(axis=1))

(5, 6)
[6. 6. 6. 6. 6.]
1.0


In [102]:
a = np.array([[1,2,3],[4,5,6]])
print(a.prod())
print(a.min())
print(a.max())
print(a.ptp())
print(a.mean())
print(a.var())
print(a.std())
print(a.argmin())
print(a.argmax())
print(np.unravel_index(a.argmax(), a.shape))

720
1
6
5
3.5
2.9166666666666665
1.707825127659933
0
5
(1, 2)


In [109]:
a = np.arange(-2, 2) ** 2
a
aa = np.array([-1,2,5,5])
aa == aa.max()
np.where(aa == aa.max())

(array([2, 3]),)

In [114]:
a = np.array([10,11,12,13,14,15]).reshape(2,-1)
a
print(a[:,::2])
a.flatten()

[[10 12]
 [13 15]]


array([10, 11, 12, 13, 14, 15])