Numpy is multi-dimensional array
1. Using fixed Type: Using less bytes of memory, No type checking 
2. Contiguous Memory: Vector Processing, Less seek time, Effective cache utilization

In [2]:
import numpy as np
import sys

In [13]:
a = np.array([1,2,3], dtype= np.int16)
print(a)
print(a.dtype)

[1 2 3]
int16


In [28]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]], dtype= np.float32)
print(b)
print(b.dtype)
print("Dimension of each array: ", a.ndim, b.ndim)
print()
print("Shape of each array: ", a.shape, b.shape)

[[9. 8. 7.]
 [6. 5. 4.]]
float32
Dimension of each array:  1 2

Shape of each array:  (3,) (2, 3)


In [29]:
print("Item Size for both: ", a.itemsize, b.itemsize)
print("Total size for both: ", a.size, b.size)

Item Size for both:  2 4
Total size for both:  3 6


In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
#### get specific element [row, column]
a[1, -5]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


10

In [36]:
## Get a specific row
print("First row:", a[0, :])
print("Second row:", a[1, :])
print("Third Column:", a[:,2])

First row: [1 2 3 4 5 6 7]
Second row: [ 8  9 10 11 12 13 14]
Third Column: [ 3 10]


In [41]:
a[0, 1:6:2]

array([2, 4, 6])

In [44]:
a[1,5] = 20
a
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [49]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print()
print(b[:,1,:])
b[0,1,1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[3 4]
 [7 8]]


4

In [56]:
## All 0s matrix
print("1st dimensional",np.zeros(5))
print("2nd dimensional",np.zeros((2,3)))
print("3rd dimensional", np.zeros((2,3,4)))
print("4th dimensional", np.zeros((2,3,4,2)))

1st dimensional [0. 0. 0. 0. 0.]
2nd dimensional [[0. 0. 0.]
 [0. 0. 0.]]
3rd dimensional [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
4th dimensional [[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [70]:
c = np.ones((2,4), dtype=np.int8)
print(c, c.dtype)
print(np.full((2,2), 99))
np.full_like(c, 41)

[[1 1 1 1]
 [1 1 1 1]] int8
[[99 99]
 [99 99]]


array([[41, 41, 41, 41],
       [41, 41, 41, 41]], dtype=int8)

In [102]:
print(np.random.rand(4,2))
print()
print(np.random.randint(7, size=(3,3)))

[[0.12195415 0.73173462]
 [0.13878247 0.76688005]
 [0.83198977 0.30977806]
 [0.59758229 0.87239246]]

[[0 5 0]
 [5 6 6]
 [5 2 6]]


In [103]:
np.random.seed(10)
print(np.random.rand(4,2))
print()
print(np.random.randint(7, size=(3,3)))

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]]

[[0 2 0]
 [6 4 3]
 [0 4 3]]


In [104]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)
arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2, 3, axis = 0)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [117]:
output = np.ones((5,5), dtype=np.int8)
print(output)
z = np.zeros((3,3), dtype=np.int8)
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print()
output

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]



array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [124]:
a = np.array([1,2,3], dtype=np.int8)
b = a.copy()
b[0] = 100
print(a) 
print()
print(b)

[1 2 3]

[100   2   3]


In [125]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [128]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
b = np.array([1,0,1,0])
print(a + b)
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[2 2 4 4]
[ 1  4  9 16]


In [132]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


Linear Algebra

In [148]:
b = np.full((3,2),2)
a = np.ones((2,3))
print(a)
print(b)
##a*b ### elementwise

np.matmul(a,b)
c = np.identity(3)
np.linalg.det(c)
d = np.array([[1,2],[5,6]])
np.linalg.det(d)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


-3.999999999999999

In [156]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
print()
print(np.min(stats, axis=1))
print()
print(np.min(stats, axis=0))
print()
print(np.max(stats, axis=1))
print()
print(np.max(stats, axis=0))

[[1 2 3]
 [4 5 6]]

[1 4]

[1 2 3]

[3 6]

[4 5 6]


In [164]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8,1))
print()
print(after)
afft = before.reshape((2,2,2))
print()
print(afft)

[[1 2 3 4]
 [5 6 7 8]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [166]:
v1  = np.array([1,2,3,4])
v2  = np.array([5,6,7,8])
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [172]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
aa = np.hstack((h1,h2,h2,h1))
aa

array([[1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.]])

In [170]:
#file = np.genfromtext('data.txt', delimeter=',')
#file.astype('np.int16')
#file = file.astype('int32')
#file

In [177]:
print(aa >= 1)
aa[aa>=1]

[[ True  True  True  True False False False False  True  True  True  True]
 [ True  True  True  True False False False False  True  True  True  True]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [184]:
print(np.any(aa > 0, axis=0))
print()
print(np.any(aa > 0, axis=1))
print()
print(np.all(aa > 0, axis=0))
print()
print(np.all(aa > 0, axis=1))

[ True  True  True  True False False False False  True  True  True  True]

[ True  True]

[ True  True  True  True False False False False  True  True  True  True]

[False False]


In [188]:
aa = aa * 2
print(aa)

[[16. 16. 16. 16.  0.  0.  0.  0. 16. 16. 16. 16.]
 [16. 16. 16. 16.  0.  0.  0.  0. 16. 16. 16. 16.]]


In [195]:
print((aa > 15) | (aa == 0))
print((aa > 15) & (aa == 0))
print(aa)

[[ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]]
[[False False False False False False False False False False False False]
 [False False False False False False False False False False False False]]
[[16. 16. 16. 16.  0.  0.  0.  0. 16. 16. 16. 16.]
 [16. 16. 16. 16.  0.  0.  0.  0. 16. 16. 16. 16.]]


In [216]:
a = np.arange(1,31, 1).reshape((6,5))
print(a)
print()
print(a[2:4,0:2])
print()
print(a[[0,1,2,3],[1,2,3,4]])
print()
print(a[-2:,-2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[11 12]
 [16 17]]

[ 2  8 14 20]

[[24 25]
 [29 30]]


In [220]:
a = [1,2,3,4,5]; b = [10,11,12,13,14]; result = []
a + b
for first, second in zip(a,b):
    result.append(first + second)
print(result)

[11, 13, 15, 17, 19]


In [233]:
a = np.array([1,2,3,4])
print(type(a))
a.dtype

f = np.array([1.2, 2.3, 4.5, 5.6])
print(d.dtype)
print(a[0])
a[0] = 2
print(a[0])
print(a)   ## all the data has to be same type since it does not check
print(a.ndim)
print()
print(a.shape)

print("Number of element of an array:", a.size)

<class 'numpy.ndarray'>
int64
1
2
[2 2 3 4]
1

(4,)
Number of element of an array: 4


In [239]:
print(a+f); print(a- f); print(a*f); print(a/f); print(a**f)
a * 10

[3.2 4.3 7.5 9.6]
[ 0.8 -0.3 -1.5 -1.6]
[ 2.4  4.6 13.5 22.4]
[1.66666667 0.86956522 0.66666667 0.71428571]
[2.29739671e+00 4.92457765e+00 1.40296115e+02 2.35253423e+03]


array([20, 20, 30, 40])

In [242]:
#Universal Functions (ufuncs)
print(np.sin(a));print(np.cos(a));print(np.tan(a))

[ 0.90929743  0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.41614684 -0.9899925  -0.65364362]
[-2.18503986 -2.18503986 -0.14254654  1.15782128]


In [255]:
a = np.arange(25).reshape((5, 5))
print(a)
print()
red = a[:,1::2]
print(red)
print()
yellow = a[-1,:]
print(yellow)
print()
blue = a[1:4:2,0:-1:2]
print(blue)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]

[20 21 22 23 24]

[[ 5  7]
 [15 17]]
